export enum AiClientErrorCode {
  THROTTLED = 'THROTTLED',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  INVALID_REQUEST = 'INVALID_REQUEST',
  AUTH_ERROR = 'AUTH_ERROR',
  MODEL_ERROR = 'MODEL_ERROR',
  TIMEOUT = 'TIMEOUT',
  STREAM_INTERRUPTED = 'STREAM_INTERRUPTED',
  CIRCUIT_OPEN = 'CIRCUIT_OPEN',
}
